baseURL: https://blog.waynekhan.net/
languageCode: en-us
title: Wayne writes
theme: loveit

params:
  app:
    title: Wayne writes

  footer:
    hugo: False
    since: 2008

  header:
    title:
      name: Wayne writes

  home:
    profile:
      subtitle: Hello, World!

  page:
    rssFullText: True
    share:
      enable: False

  social:
    GitHub: waynekhan
    Linkedin: waynekhan

  title: Wayne writes
  description: I create (and update) posts occasionally, mostly for myself then
