baseURL: https://blog.waynekhan.net/
languageCode: en-us
title: Wayne writes
theme: loveit

params:
  app:
    title: Wayne Khan

  footer:
    hugo: false
    since: 2008

  header:
    title:
      name: Wayne Khan

  home:
    profile:
      subtitle: Hello, World!

  page:
    rssFullText: true
    share:
      enable: false

  social:
    GitLab: waynekhan
    Linkedin: waynekhan

  title: Wayne writes
  description: I write very occasionally, mostly as a note to self but it might be useful for you too
